'''
Module: ediff.pcryst
--------------------

Process polycrystalline/powder diffraction patterns.

* XRD powder diffractograms are *calculated* from a structure or CIF-file.
* ELD powder diffractograms are *converted* from 2D images to 1D profiles.
* Note: XRD/PXRD = (powder) X-ray diffraction; ELD = electron diffraction.

Key classes in this module:
    
* ediff.pcryst.XRD_polycrystal =
  calculation of a *theoretical* powder X-ray diffraction pattern.
* ediff.pcryst.ELD_polycrystal =
  processing of an *experimental* 2D powder electron diffration pattern.
* ediff.pcryst.Comparison =
  comparison of the XRD and ELD profiles from the previous two steps/classes.

List of all classes in this module:

* Crystal, SimuParams, PlotParams, PeakProfile
  = classes that define parameters for PXRDcalculation.
* PXRDcalculation = calculation of
  the theoretical XRD difractogram (basic API).
* PXD_polycrystal = calculation of
  the theoretical XRD diffratogram (object-oriented API).
* ELD_polycrystal = complete processing of
  the experimental ELD diffractogram (object-oriented API).
* Comparison = final comparison
  of the processed XRD and ELD profiles.
'''


import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import convolve as spConvolve
from pymatgen.core.structure import Structure as pmStructure
from pymatgen.analysis.diffraction.xrd import XRDCalculator as pmXRDCalculator

import ediff.io
import ediff.center
import ediff.pcryst


class Crystal:
    '''
    Define crystal structure.
    
    Parameters
    ----------
    structure : structure object
        * The *structure object* is usually obtained from a CIF-file
          (CIF = Crystallographic Information File).
        * The *CIF files* are available in crystallographic databases,
          such as http://www.crystallography.net
        * The exact type of the object is *pymatgen.core.structure.Structure*
              * This indicates that the structure is read from CIF by means of
                pymatgen package (which works behind the sceenes).
              * This also means that the structure can be created by any
                other way available in pymatgen https://pymatgen.org/
              * It is also possible to define structure in ediff.io,
                using ediff.io.Lattice and ediff.io.Structure objects.
              * Nevertheless, for common usage it is enough to
                read the structure from CIF, ignoring technical details.
    temp_factors : float or dictionary, optional, the default is 0.8
        * Temperature factors characterize thermal movement of atoms.
        * If a float value is given,
          all elements have this temperature factor value.
        * If a dictionary is given,
          the elements have the values defined in the dictionary;
          a sample input dictionary: `temp_factors = {'Na':1.2, 'Cl':1.1}`.
    '''

    
    def __init__(self, structure, temp_factors=0.8):
        '''
        * Initialize Crystal object.
        * The parameters are described above in class definition.
        '''
        # (1) Define structure
        if type(structure) == pmStructure:
            # Structure was generated by PyMatGen methods
            self.structure = structure
        else:
            # Structure is not from PyMatGen => we suppose CIF input
            self.structure = self.read_structure_from_CIF(structure)
        # (2) Define temperature factors
        if type(temp_factors) == dict:
            # Temperature factors were given as dictionary
            self.temp_factors = temp_factors
        else:
            # Temp.factors are not dictionary => we suppose a number
            # (the number is a universal temperature factor for all atoms
            self.temp_factors = self.get_elements_with_temp_factors(
                self.structure, temp_factors)

    
    @staticmethod
    def read_structure_from_CIF(CIF):
        '''
        Read crystall structure from CIF file.

        Parameters
        ----------
        CIF : str or path object
            * The filename of CIF file.
            * CIF = Crystallographic Information File
              contains information about crystal structure.
            * CIF files are usually obtained from crystallographic databases,
              such as http://www.crystallography.net

        Returns
        -------
        structure : structure object
            * The exact type of the object is
              *pymatgen.core.structure.Structure*.
            * Nevertheless, in the structure objects are usually
              created from CIF files (pymatgen is hidden for a common user).
         '''
        structure = pmStructure.from_file(CIF)
        return(structure)


    def get_elements(self, structure):
        '''
        Get a list of all elements, which are contained in given structure.

        Parameters
        ----------
        structure : structure object
            Typically, the structure objects are
            created by function *read_structure_from_CIF* above.

        Returns
        -------
        list_of_elements : list
            List with symbols of all elements
            that are present in given *structure*.
            
        Technical note
        --------------
        * The elements are obtained from *structure* object.
        * The structure object = pymatgen.core.structure.Structure.
        * The list of element names si obtained by a set of tricks
          specific to pymatgen-structure object.
        * These tricks were revealed by inspecting the original
          pymatgen.core.structure.Structure in Spyder,
          by means of shortcuts Ctrl+I (help) and Ctrl+G (go to code).
        * Common users do not have to use this function.
        * The function is just used internally, when setting
          temperature factors of the elements contained in given *structure*.
        '''
        list_of_atoms = []
        for site in structure:
            for sp, occu in site.species.items():
                list_of_atoms.append(sp.symbol)
        list_of_elements = np.unique(list_of_atoms)
        return(list_of_elements)


    def get_elements_with_temp_factors(self, structure, B=0.8):
        '''
        Get a dictionary, which contains symbols and temperature factors
        of all elements, which are present in given structure.

        Parameters
        ----------
        structure : structure object
            Typically, the structure objects are
            created by function *read_structure_from_CIF* above.
        B : float, optional, the default is 0.8
            

        Returns
        -------
        elements_with_temp_factors : dict
            Dictionary with symbols and temperature factors
            of all elements, which are present in given *structure*.
            
        Notes
        -----
        * The dictionary is in the format required by pymatgen package.
        * The pymatgen package is used for PXRD calculations,
          but these calculations are hidden from common users.
        * Common users do not use this function.
        * The function is just used internally, when setting
          temperature factors of the elements contained in given *structure*.
         '''
        elements = self.get_elements(structure)
        elements_with_temp_factors = dict.fromkeys(elements, B)
        return(elements_with_temp_factors)


class SimuParams:
    '''
    Define simulation parameters = params for theoretical PXRD calculations.
    
    Parameters
    ----------
    wavelength : float
        Wavelength of the X-rays.
        Typical values are 1.54 A (CuKa) or 0.71 A (MoKa).
    two_theta_range: list/tuple of two floats
        Minimal and maximal diffraction angle;
        both values are TwoTheta angle in [deg] (for given *wavelength*).
    peak_profile : ediff.pcryst.PeakProfiles object, optional
        Profile of the calculated diffraction peaks.
        The default is ediff.pcryst.PeakProfiles.pseudo_voigt.
        This default is suitable for common calculations
        and does not have to be changed (in great majority of cases).
    peak_profile_sigma : float, optional, the default is 0.03
        Width of the calculated diffraction peaks.
        The default = 0.03 is suitable for most of common calculations
        and corresponds to the default in older PowderCell program.
        For overlapping peaks it may be slightly decreased,
        while for more realistic diffractograms it may be slightly increased.  
    '''

    def __init__(self, wavelength, two_theta_range, 
                 peak_profile = None, peak_profile_sigma = 0.03):
        '''
        * Initialize Experimental object.
        * The parameters are described above in class definition.
        '''
        
        # Initialize the first two parameters
        self.wavelength = wavelength
        self.two_theta_range = two_theta_range

        # Initialize the third parameters
        # ! TRICK: default should be PeakProfiles.pseudo_voigt
        #   BUT at the time of importint this is not fully known
        #   SOLUTION (recommended by AI): we use None as default value
        #   ...and decide later (=after import) if we replace it with default
        if peak_profile is not None:
            self.peak_profile = peak_profile
        else:
            self.peak_profile = PeakProfiles.pseudo_voigt
        
        # Initialize the last/remaining parameter
        self.peak_profile_sigma = peak_profile_sigma
                    

class PlotParams:
    '''
    Define parameters for plotting within PXRDcalculation class.
    
    * This is a very simple class.
    * It is employed when initializing PXRDcalculation object.
    * It is kept for convenience, old scripts and backward compatibility.
    
    Parameters
    ----------
    title : str
        Title of the plot.
    x_axis : str, 'TwoTheta','S','q' or 'dhkl', optional, default is 'q'
        What should be shown on X-axis (diff.angle, diff.vector ...).
        During the processing, the data are adjusted according this argument.
    xlim : tuple of two numbers
        Range of X-axis = xlim parameter from matplotlib.pyplot.
    '''
    

    def __init__(self, title=None, x_axis='q', xlim=None):
        '''
        * Initialize PlotParameters object.
        * The parameters are described above in class definition.
        '''
        
        # Initialize basic parameters
        self.title = title
        self.x_axis = x_axis
        self.xlim = xlim


class PeakProfiles:
    '''
    Define profile of diffraction peaks.

    * This class is employed only as a namespace.
    * It contains three functions/definitions of diffratction peak profiles.
    '''


    def gaussian(X,m,s):
        '''
        Gaussian function (~ profile for PXRD calculation).
    
        Parameters
        ----------
        X : numpy array
            X-variable of Gaussian function.
        m : float
            Mean value = the center of Gaussian function.
        s : float
            Standard deviation = the width of Gaussian function.
    
        Returns
        -------
        NumPy array
            The array with Y-values of the function; Y = Gaussian(X).
        '''
        return( 1/(s*np.sqrt(2*np.pi)) * np.exp(-(X-m)**2/(2*s**2)) )
    

    def lorentzian(X,m,s):
        '''
        Lorentzian function (~ profile for PXRD calculation).
    
        Parameters
        ----------
        X : numpy array
            X-variable of Lorentzian function.
        m : float
            Mean value = the center of Lorentzian function.
        s : float
            Standard deviation = the width of Lorentzian function.
    
        Returns
        -------
        NumPy array
            The array with Y-values of the functin; Y = Lorenzian(X).
        '''
        return( 1/np.pi * s/((X-m)**2 + s**2) )
    

    def pseudo_voigt(X,m,s,n=0.5):
        '''
        Pseudo-Voigt function (~ profile for PXRD calculation).
    
        Parameters
        ----------
        X : numpy array
            X-variable of pseudo-Voigt function.
        m : float
            Mean value = the center of pseudo-Voigt function.
        s : float
            Standard deviation = the width of pseudo-Voigt function.
        n : float, optional, the default is 0.5
            Ratio between Gaussian and Lorentzian components.
            In the very first approximation, we can set n = 0.5.
            For more details, see *Notes* subsection below.
            
        Returns
        -------
        NumPy array
            The array with Y-values of the functin; Y = Lorenzian(X).
    
        Notes
        -----
        * Pseudo-Voigt function
          = linear combination of Gaussian and Lorentzian function.
        * In the 1st approximation:
            * 50/50 combination => n = 0.5
            * sg = sigma_Gaussian
              defined so that sg and s yielded the same FWHM
        * more details in:
            * https://en.wikipedia.org/wiki/Voigt_profile
            * https://lmfit.github.io/lmfit-py/builtin_models.html
        '''
        # (1) Calculate sg
        # (sg = sigma_Gaussian - see docstring above for more details
        sg = s/np.sqrt(2*np.log(2))
        # (2) Calculate Pseudo-Voigt function
        # (Pseudo-Voigt = n * Gausian + (1-n) * Lorenzian)
        pseudo_voigt = \
            n * PeakProfiles.gaussian(X,m,sg) \
            + (1-n) * PeakProfiles.lorentzian(X,m,s)
        # (3) Return calculated function    
        return(pseudo_voigt)



class PXRDcalculation:
    '''
    Class yielding PXRDcalculation object.
    
    * PXRDcalculation object = calculated powder X-ray difractogram/profile.
    * Based on: https://pymatgen.org/pymatgen.analysis.diffraction.html
    * Adjusted to provide simple, user-friendly API, as shown below.
    * Even simpler API: see ediff.pcryst.XRD_polycrystal class.
    '''
   
    def __init__(self, crystal, 
                 simu_parameters, plot_parameters, peak_profile_sigma = None):
        '''
        Initialize PXRDcalculatin object.
        
        Parameters
        ----------
        crystal : ediff.pcryst.Crystal object
            This object is usually prepared in advance
            as an instance of ediff.pcryst.Crystal class.
        simu_parameters : ediff.pcryst.Simu_params object
            This object is usually prepared in advance
            as an instance of ediff.pcryst.Simu_params class.        
        plot_parameters : ediff.pcryst.PlotParameters object
            This object is usually prepared in advance
            as an instance of ediff.pcryst.PlotParameters class.
        peak_profile_sigma : float, optional, the default is None
            Width of the calculated diffraction peaks.
            If the parameter is not given,
            the default from the simu parameters is used.
            See ediff.pcryst.SimuParams class for details. 
        
        Returns
        -------
        PXRDcalulation object
            The object can be used to show/save diffraction
            or the whole diffraction pattern, as shown below.
            Even easier API is provided by ediff.pcryst.XRD_polycrystal class.
        
        Example
        -------
        >>> # EDIFF :: calculate diffraction pattern of NaCl
        >>>
        >>> import ediff.pcryst as pcryst
        >>>
        >>> # [0] Crystal structure is usually defined
        >>> # by means of CIF = Crystallographic Information File.
        >>> # CIFs can be downloaded from: https://www.crystallography.net
        >>> CIF_FILE = r'./nacl_1000041.cif'
        >>> 
        >>> # [1] Crystal, experimental and plot parameters
        >>> # are defined as objects XTAL, EPAR, and PPAR, respectively.
        >>> XTAL = pcryst.Crystal(structure=CIF_FILE, temp_factors=0.8)
        >>> SPAR = pcryst.SimuParams(wavelength=0.71, two_theta_range=(5,120))
        >>> PPAR = pcryst.PlotParams(x_axis='q', xlim=(1,10))
        >>> 
        >>> # [2] PXRDcalculation object
        >>> # calculates PXRD when called/initialized
        >>> # and contains the results for further processing.
        >>> CALC = pcryst.PXRDcalculation(
        >>>     XTAL,SPAR,PPAR, peak_profile_sigma=0.1)
        >>> 
        >>> # [3] Show/save CALCulation results.
        >>> # (it is quite Ok to use the default settings of EDIFF package
        >>> # (more advanced plotting => use saved results + arbitrary SW
        >>> CALC.print_diffractions()
        >>> CALC.save_diffractions('nacl_pxrd.py.diff')
        >>> CALC.plot_diffractogram('nacl_pxrd.py.png')
        >>> CALC.save_diffractogram('nacl_pxrd.py.txt') 
        '''
        
        # Key parameters
        self.crystal = crystal
        self.simu_parameters = simu_parameters
        self.plot_parameters = plot_parameters
        
        # 
        if peak_profile_sigma is not None:
            self.peak_profile_sigma = peak_profile_sigma
            self.simu_parameters.peak_profile_sigma = peak_profile_sigma
        else:
            self.peak_profile_sigma = self.simu_parameters.peak_profile_sigma
        
        # Calculate diffractions
        # (PyMatGen calculation = call adjusted external function
        self.diffractions = self._calculate_diffractions()
        
        # Calclate whole diffraction profile
        # (our own calculation = diffractions convoluted with peak_profile
        # (peak_profile parameters are defined within sumu_parameters
        self.profile = self._calculate_diffraction_profile()

    def _calculate_diffractions(self):
        # Private method.
        # During the initialization,
        #  this method calculates diffractions by means of PyMatGen.
        # The calculated diffractions
        #  are saved in self.diffractions
        #  and used in the next step of the initialization
        #  to calculate diffraction profile, which is saved in self.profile.
        # -----
        
        # (1) Calculate intensities
        calculation = pmXRDCalculator(
            wavelength = self.simu_parameters.wavelength,
            debye_waller_factors=(self.crystal.temp_factors))
        diffractions = calculation.get_pattern(
            self.crystal.structure,
            two_theta_range = self.simu_parameters.two_theta_range)
        
        # (2) Transform diffractions: PyMatGen structure => pd.DataFrame
        diffractions_df = self._diffractions_to_dframe(diffractions)
        
        # (3) Return calculated diffractions
        # (pandas.DataFrame with cols: TwoTheta, h,k,l, dhkl, S, q, Intensity
        return(diffractions_df)
        

    def _calculate_diffraction_profile(self):
        # Private method.
        # During the initialization,
        #  this method calculates diffraction profile from self.diffractions.
        # The calculation does not need PyMatGen any more:
        #  - PyMatGen is employed only in calculation of self.diffractions
        #  - the self.profile is calculated by *convolution*
        #    of self.diffractions and self.peak.profile_type
        # -----
        
        # The method calculates 
        # (1) Base diffraction profile
        # = diffractogram with zero intensities
        # = interval theta_min to theta_max with step=0.001, zero intensities
        th1,th2 = th1,th2 = self.simu_parameters.two_theta_range
        numpoints = (th2-th1) * 100 + 1
        diffractogram_2theta = np.linspace(th1, th2, numpoints, endpoint=True)
        diffractogram_intensity = np.zeros(len(diffractogram_2theta))
        df = pd.DataFrame(
            np.transpose([diffractogram_2theta, diffractogram_intensity]),
            columns=['TwoTheta','Intensity'])
        
        # (2) Line diffraction pattern
        # = diffractogram with line intensities
        # (2a) read diffractions, rounded to 3 dec.places ~ step 0.001
        diffractions = np.round(
            np.array(self.diffractions[['TwoTheta','Ihkl']]),2)
        # (2b) insert line diffractions into zero profile from step (1)
        for two_theta, intensity in diffractions:
            # calculate index = position of the diffraction in profile array
            index = int(round((two_theta - th1) * 100))
            # insert the diffraction intensity at calculated position
            df.Intensity[index] = intensity
        
        # (3) Simulated diffraction profile
        # = diffractogram with intensity profiles
        # (3a) Is peak_profile_type defined?
        # (Argument {peak_profile_type} has default value - pseudo_voight
        # (Therefore, it should be defined unless user specifies None value
        if self.simu_parameters.peak_profile == None:
            print('Error: peak_profile_type is not defined!')
            sys.exit()
        # (3b) The peak_peak_profile_type is defined => calculate difractogram
        # Precalculate peak profile
        X = np.linspace(-10,10,2001,endpoint=True)
        peak_profile = self.simu_parameters.peak_profile(
            X, 0, self.simu_parameters.peak_profile_sigma)    
        peak_profile = peak_profile/np.max(peak_profile)
        # Convolve Intensities with PeakProfile
        df.Intensity = spConvolve(df.Intensity,peak_profile, mode='same')
        # Normalize the calculated intensities
        # (The normalization is not strictly necessary,
        # (as spConvolve defined above keeps the original normalization,
        # (but the normalization to 1 is convenient for further processing.
        df.Intensity = df.Intensity/np.max(df.Intensity)
        
        # (4) Add columns with diffraction vectors (S, q)
        # (the calculated profile has two columns: TwoTheta, Intensity
        # (now we insert two additional cols to get: TwoTheta, S, q, Intensity
        # ---
        # Prepare wavelenght (just shortcut for convenience)
        wavelength = self.simu_parameters.wavelength
        # Insert a column with the calculated values of diffration vector S
        df.insert(loc = 1, column = 'S',
            value = 2*np.sin(df.TwoTheta/2*np.pi/180) / wavelength)
        # Insert a column with the calculated values of difraction vector q
        df.insert(loc = 2, column = 'q', 
            value = 2*np.pi * df.S)

        # (5) Return diffractogram = the whole diffraction profile
        return(df)
        
    
    @staticmethod
    def _diffractions_to_dframe(intensities):
        # Private method.
        #  Converts the calculated PyMatGen structure (intensities)
        #  to standard DataFrame (which is then saved in self.diffractions).
        # -----
        
        # Prepare hkl indexes
        h = []; k = []; l = []
        
        # Test if the structure is hexagonal
        hexagonal = (len(intensities.hkls[0][0]['hkl']) == 4)
        # ...and if the structure is hexagonal, prepare i-index (hkl) -> (hkil)
        if hexagonal: i = []
        
        # Fill in hkl (or hkil) indexes
        for ints in intensities.hkls:
            h.append(ints[0]['hkl'][0])
            k.append(ints[0]['hkl'][1])
            if not(hexagonal):
                l.append(ints[0]['hkl'][2])
            else:    
                i.append(ints[0]['hkl'][2])
                l.append(ints[0]['hkl'][3])
        
        # Create DataFrame from all values
        # (again, we have to consider hexagonal structures => hkil indexes
        if not(hexagonal):
            df = pd.DataFrame( 
                np.transpose(
                    [intensities.x,
                     h, k, l, intensities.d_hkls, intensities.y]),
                columns=['TwoTheta','h','k','l','dhkl','Ihkl'])
            df.insert(loc=5, column='S', value=1/df.dhkl)
            df.insert(loc=6, column='q', value=2*np.pi*df.S)
        else:
            df = pd.DataFrame( 
                np.transpose(
                    [intensities.x,
                     h, k, i, l, intensities.d_hkls, intensities.y]),
                columns=['TwoTheta','h','k','i', 'l','dhkl','Ihkl'])
            df.insert(loc=6, column='S', value=1/df.dhkl)
            df.insert(loc=7, column='q', value=2*np.pi*df.S)
        
        # Return the final dataframe
        return(df)

    
    @staticmethod
    def _diffractions_to_table(dframe):
        # Private method.
        #  Converts DataFrame with diffractions (saved in self.diffractions)
        #  to table that suitable for printing (stdout) or saving (to a file).
        # -----
        
        # POZOR: parametr formatters je zaludny!
        # * musi to byt sada funkci, takze...
        #   NEfunguji string-formaty '%.3f' - nejsou to funkce
        #   NEfunguji f-stringy - nelze prazdne - f'{8.3f}' ani f'{:8.3f}'
        # * muzou se pouzit funkce str.format nebo lambda funkce
        #   to uz je skoro jednodussi str.format
        #   trik #0: obecne formaty nahrazovaciho pole ve str.format
        #       {}, {nazev_pole}, {nazev_pole:specifikace_formatu} ...
        #       pricemz v nasem pripade mame {:specifikace_formatu}
        #       takze odtud se tam vezme ta zdanlive mysticka dvojtecka
        #   trik #1: float M.N-format je bez carky '{:8.3f}'.format
        #       ale: float  .N-format je s carkou  '{:,.3f}'.format
        #   trik #2: NElze naformatovat obecny typ jako integer
        #     takze: pro obecne cislo misto NEfunkcniho {:3d} nutno {:3.0f}
        # ------
        
        # Test if the structure is hexagonal
        hexagonal = (len(dframe.columns) == 9)
        
        # Different formatting for non-hexagonal and hexagonal structures.
        # (reason: in PyMatGen, hexagonal structures use four-index notation
        if not(hexagonal):
            # (a) Non-hexagonal structure => hkl indexes (standard)
            table = dframe.to_string(
                index = False,
                formatters = {
                    'TwoTheta' : '{:8.3f}'.format,
                    'h'        : '{:3.0f}'.format,
                    'k'        : '{:3.0f}'.format,
                    'l'        : '{:3.0f}'.format,
                    'dhkl'     : '{:7.3f}'.format,
                    'S'        : '{:7.3f}'.format,
                    'q'        : '{:7.3f}'.format,
                    'Ihkl'     : '{:9.3f}'.format})
        else:
            # (b) Hexagonal structure => hkil indexes (four, non-standard)
            table = dframe.to_string(
                index = False,
                formatters = {
                    'TwoTheta' : '{:8.3f}'.format,
                    'h'        : '{:3.0f}'.format,
                    'k'        : '{:3.0f}'.format,
                    'i'        : '{:3.0f}'.format,
                    'l'        : '{:3.0f}'.format,
                    'dhkl'     : '{:7.3f}'.format,
                    'S'        : '{:7.3f}'.format,
                    'q'        : '{:7.3f}'.format,
                    'Ihkl'     : '{:9.3f}'.format})
        
        # Return the formated table
        return(table)
    
    
    @staticmethod
    def _diffractogram_to_table(dframe):
        # Private method.
        #  Converts DataFrame with diffraction profile (saved in self.profile)
        #  to table that suitable for saving (to a file).
        # ------
        
        # Format the dataframe containing diffraction profile as table.
        table = dframe.to_string(
            index = False,
            formatters = {
                'TwoTheta'  : '{:7.2f}'.format,
                'S'         : '{:9.5f}'.format,
                'q'         : '{:9.5f}'.format,
                'Intensity' : '{:7.4f}'.format})
        
        # Return the formated table
        return(table)

    
    @staticmethod
    def _set_plot_details(title, x_axis, xlim):
        # Private method.
        # ------
        
        # (1) Set plot title
        # (only if it is defined
        if title != None: plt.title(title)
        
        # (2) Set xlimits = xlim
        # (only if they are defined
        if xlim != None: plt.xlim(xlim)
        
        # (3) Determine label of x-axis = xlabel.
        # (this is always defined, as its default value is 'q'
        if (x_axis == 'q') or (x_axis == 'S'):
            xlabel_str = f'${x_axis}$' + r' [1/$\mathrm{\AA}$]'
        elif x_axis == 'TwoTheta':
            xlabel_str = r'2$\theta$ [deg]'
        elif x_axis == 'dhkl':
            xlabel_str = r'$d(hkl)$' + r' [$\mathrm{\AA}$]'
        else:
            print('X-axis - unknown quantity and units...')
        
        # (4) Set the remaining plot details
        # (change Jupyter default transparent color to white
        plt.gcf().patch.set_facecolor('white')
        # (do the rest: XY-labels, grid, tight_layout...
        plt.xlabel(xlabel_str)
        plt.ylabel('Intensity')
        plt.grid()
        plt.tight_layout()


    def print_diffractions(self):
        '''
        Print the calculated diffractions to stdout.
        
        Parameters
        ----------
        None
            It just prints the (formatted) content of self.diffractions.
        
        Returns
        -------
        None
            The output is printed on the screen/stdout.
        '''
        table = PXRDcalculation._diffractions_to_table(self.diffractions)
        print(table)
            

    def plot_diffractions(self, outfile=None, dpi=300, 
                          title=None, x_axis=None, xlim=None):
        '''
        Plot the calculated diffractions.
        
        Parameters
        ----------
        outfile : str, optional, the default is none
            Name of the output file.
            If not given, the plot is just shown, but not saved.
        dpi : int, optional, default is 300
            DPI of the output file.
            Taken into account only if *output_file* is not None.
        title : str, optional, default is None
            Title of the plot.
        x_axis : 'q' or 'S' or 'TwoTheta' or 'dhkl' or None
            Optional parameter, default is None,
            but the default used during initialization is 'q'.
            If the default value is not changed here,
            the initialization default will be employed and x_axis will be 'q'.
        xlim : tuple of two floats or None, default is None
            Optional parameter, default is None.
            If given, it limits the x-range = x-limits of the plot.
        
        Returns
        -------
        None
            The output is the plot on the screen (and outfile).
            This function plots just diffraction intensities
            at correct positions, not the whole diffraction profile.
            To plot the whole diffraction profile,
            i.e the difraction intensities convoluted with peak profiles,
            use ediff.pcryst.plot_diffractions method.
        '''
        
        # (0) Data to plot
        df = self.diffractions
        
        # (1) Plot parameters
        # (some might have been predefined during initialization => in self
        # (some might have been re-defined during the call of this function
        my_title  = title  or self.plot_parameters.title
        my_x_axis = x_axis or self.plot_parameters.x_axis
        my_xlim   = xlim   or self.plot_parameters.xlim
        
        # (2) Prepare the plot
        plt.vlines(df[my_x_axis], 0, df['Ihkl'], lw=2)
        
        # (3) Set plot details
        # (external function, common to diffractions and diffractogram plots
        self._set_plot_details(my_title, my_x_axis, my_xlim)
        
        # (4) Save/show the plot...
        # In Spyder: plot is always shown
        # In CLI: plot is saved (if outfile is defined) or it is just shown
        if outfile != None: 
            plt.savefig(outfile, dpi=dpi) 
        else:
            plt.show()
        

    def save_diffractions(self, outfile):
        '''
        Save the calculated diffractions to *outfile*.
        
        Parameters
        ----------
        output_file : str
            Name of the output file.

        Returns
        -------
        None
            The output is the list of diffractions in the *outfile*.
        '''
        try:
            with open(outfile, 'w') as fh:
                table = \
                    PXRDcalculation._diffractions_to_table(self.diffractions)
                print(table, file=fh)
        except:
            print(f'Error saving diffractions to {outfile}!')
            

    def plot_diffractogram(self, outfile=None, dpi=300,
                           title=None, x_axis=None, xlim=None):
        '''
        Plot the calculated diffractogram = the comlete diffraction profile.        

        Parameters
        ----------
        outfile : str, optional, the default is none
            Name of the output file.
            If not given, the plot is just shown, but not saved.
        dpi : int, optional, default is 300
            DPI of the output file.
            Taken into account only if *output_file* is not None.
        title : str, optional, default is None
            Title of the plot.
        x_axis : 'q' or 'S' or 'TwoTheta' or 'dhkl' or None
            Optional parameter, default is None,
            but the default used during initialization is 'q'.
            If the default value is not changed here,
            the initialization default will be employed and x_axis will be 'q'.
        xlim : tuple of two floats or None, default is None
            Optional parameter, default is None.
            If given, it limits the x-range = x-limits of the plot.
        
        Returns
        -------
        None
            The output is the plot on the screen (and outfile).
        '''
        
        # (0) Data to plot
        df = self.profile
        
        # (1) Plot parameters
        # (some might have been predefined during initialization => in self
        # (some might have been re-defined during the call of this function
        my_title  = title  or self.plot_parameters.title
        my_x_axis = x_axis or self.plot_parameters.x_axis
        my_xlim   = xlim   or self.plot_parameters.xlim
        
        
        # (2) Prepare the plot
        plt.plot(df[my_x_axis], df['Intensity'])
        
        # (3) Set plot details
        # (external function, common to diffractions and diffractogram plots
        PXRDcalculation._set_plot_details(my_title, my_x_axis, my_xlim)
        
        # (4) Save/show the plot...
        # In Spyder: plot is always shown
        # In CLI: plot is saved (if outfile is defined) or it is just shown
        if outfile != None: 
            plt.savefig(outfile, dpi=dpi) 
        else:
            plt.show()


    def save_diffractogram(self, outfile):
        '''
        Save the calculated diffarctogram = whole diff.profile to *outfile*.

        Parameters
        ----------
        outfile : str
            Name of the output file.

        Returns
        -------
        None
            The output is the complete diffraction profile saved in *outfile*.
        '''
        try:
            with open(outfile, 'w') as fh:
                table = \
                    PXRDcalculation._diffractogram_to_table(self.profile)
                print(table, file=fh)
        except:
            print(f'Error saving diffraction profile to {outfile}!')    


    def plot_indexed_diffractions(self, output_file=None, two_theta=None):
        '''
        Plot diffractions with their dffraction indices.
        
        * This function (usually) creates an interactive plot.
        * *In CLI* (command line) - the plot is interactive automatically.
        * *In Spyder or Jupyter* - type the following *magic commands*:
            * BEFORE running (switch on the interactive mode): %matplotlib qt
            * AFTER running (back to non-interactive mode): %matplotlib inline
            * In Spyder, the commands are typed in the Console window.
            * In Jupyter, the commands are usually typed in separate cells.
        
        Parameters
        ----------
        output_file: str, optional, default is None
            If the argument is not None, the output is saved to {output_file}.
            This argument is usually not needed, as the interactive plot
            is rather for inspecting the diffraction indices than for saving.
        two_theta: tuple of two floats, optional, default is None
            If the argument is None, the plot uses the default two_theta
            range (saved in self.experiment.two_theta).
            IF the parameter is not None, it determines the two theta range
            for the plot.
            
        Returns
        -------
        None
            The output is the plot in the screen or in the {output_file}.
            In a typical case, the plot is interactive
            so that the indexed diffractions could be inspected in detail.
        
        Technical notes
        ---------------
        * The code below uses (sligthly modified) PyMatGen functions.
            - Reason: PyMatGen plots with diffraction indexes are quite good.
            - Re-programing would be quite difficult, boring, and useless.
        * The direct usage of PyMatGen function is a kind of exception.
            - PyMatGen function is used during the initialization.
            - Then we rely on our own functions as much as possible.
            - Reason: PyMatGen functions may change, we want an independence.
            - Here: As noted above - PyMatGen function saves a lot of work.
        * The function is usually called without args to get interactive plot.
            - Additional arguments are not necessary.
            - {output_file} and {theta_range} can modify default plot params
        '''
        
        # (0) Redefine plot parameters
        # (so that they were optimized for the interactive plot
        original_rcParams = plt.rcParams
        plt.rcParams.update({
            'figure.figsize'  : (12/2.54,4/2.54),
            'figure.dpi'      : 200,
            'font.size'       : 6})
        
        # (1) Calculate diffractions
        # (re-calculation in order to get the original PyMatGen xrd object
        # (the xrd object can be employed to plot diffractions with indexes
        xrd = pmXRDCalculator(
            wavelength = self.simu_parameters.wavelength,
            debye_waller_factors=(self.crystal.temp_factors))
        
        # (2) Create plot with indexes
        # (trick: we create figure and axes (fig,ax)
        # (and instruct PyMatGen to plot in pre-defined axes
        # (a) prepare fig,ax
        fig,ax = plt.subplots()
        # (b) prepare two_theta range 
        if two_theta is None: two_theta = self.simu_parameters.two_theta_range
        # (c) create the plot using the parameters from (a,b) 
        xrd.get_plot(
            structure = self.crystal.structure,
            two_theta_range=two_theta,
            annotate_peaks='compact', ax=ax, fontsize=6)
        
        # (3) Ex-post changing line properties in plt.plot
        # https://stackoverflow.com/q/41709257
        for line in ax.get_lines():
            line.set_color('orange')
        ax.set_xlabel('2theta [deg]')
        ax.set_ylabel('Intensity')
        ax.grid()
        
        # (4) Set higher number of ticks on X-axis
        # Trick #1: major ticks => higher MaxNLocator to get dense ticks
        # Trick #2: minor ticks => import special class for them
        ax.xaxis.set_major_locator(plt.MaxNLocator(15, steps=[1,2,5,10] ))
        from matplotlib.ticker import AutoMinorLocator
        ax.xaxis.set_minor_locator(AutoMinorLocator(5))
        
        # (5) Final adjustments
        fig.tight_layout()
        
        # (6) Show  or save the plot, depending on output_file argument
        # (note: default is output_file=None => plot is shown, not saved
        # (reason: this func is usually used for interactive plots
        if output_file is None:
            plt.show()
        else:
            plt.savefig(output_file, dpi=300)
        
        # (7) Revert to original rcParams.
        plt.rcParams.update(original_rcParams)


class XRD_polycrystal(PXRDcalculation):
    '''
    Class yielding *XRD_polycrystal* objects.
    
    * *XRD_polycrystal* object is a wrapper of *PXRDcalculation* class.
    * It runs PXRDcalculation in one step and returns PXRDcalculation object.
    * In fact, the PXRDcalculation and PXRD_polycrystal objects are indentical.
    * Main advantage of XRD_polycrystal - simpler API than PXRDcalculation.
    '''
    
    def __init__(self, structure, temp_factors=0.8, description=None, 
                 wavelength = 0.71, two_theta_range = (5,100),
                 peak_profile = PeakProfiles.pseudo_voigt,
                 peak_profile_sigma = 0.03,
                 plot_params = {'title':None, 'x_axis':'q', 'xlim':None}):
        '''         
        Initialize *XRD_polycrystal* object  

        Parameters
        ----------
        structure : CIF-file or ediff.io.Structure object
            Definition of the crystal structure.
            The crystal structure can be defined by means of
            CIF-file or Structure object.
            More info about CIF-files is in ediff.pcryst.Crystal class.
            The Structure objects are described in ediff.io.Structure class.
        temp_factors : float, optional, default is 0.8
            The temperature factor, common for all atoms.
            The value of 0.8 is a reasonable default.
            It is possible (but usually not necessary) to specify
            temperature factors for the invividual atoms in the structure,
            in the form of dictionary, as described in ediff.io.Crystal class.
        description : str, optional, default is None 
            The (short) text description of the crystal structure,
            from which the powder diffraction pattern is calculated.
            Non-obligatory, but useful for documentation and clarity.
        wavelength : float, optional, default is 0.71
            Wavelength of X-rays (in Angstrem), which is used
            for the calculation of the powder diffractogram.
            The default corresponds to commonly used MoKa radiation.
        two_theta_range : tuple of two floats, optional, default is (5,100)
            The minimum and maximum value of 2*theta
            (where theta is the diffraction angle)
            that are used for the calculation of diffractions
            (diffractions outside the interval are ignored).
        peak_profile : ediff.pcryst.PeakProfiles object, optional
            Profile of the calculated diffraction peaks.
            The default is ediff.pcryst.PeakProfiles.pseudo_voigt.
            This default is suitable for all common calculations
            and does not have to be changed (in great majority of cases).
        peak_profile_sigma : float, optional, default is 0.03
            Width of the calculated diffraction peaks.
            It can be slightly increased in case of non-overlapping peaks.
            See ediff.pcryst.SimuParams class for details.
        plot_params : dict, optional
            The dictionoary collecting ediff.pcryst.Plot_params parameters.
            The default is {'title':None, 'x_axis':'q', 'xlim':None}.
            In most cases, this dictionary does not have to be changed.

        Returns
        -------
        XRD_polycrystal object
            The {XRD_polycrystal} object is identical to
            the {PXRDcalculation} object.
            It has the same methods and properties, including two key
            properties, which are auto-calculated during the initialization
            = {diffractions} and {profile}.
            The {XRD_polycrystal} object can use all inherited methods
            from ediff.pcryst.PXRDcalculation object or employ any other
            functions to work with the properties, as shown below.
             
        Example
        -------
        
        >>> # (0) Import EDIFF
        >>> import ediff as ed
        >>>
        >>> # (1) Calculate PXRD = PXRDcalculation object
        >>> XRD = ed.pcryst.XRD_polycrystal(
        >>>     description = 'Au,fcc :: theoretical diffractogram',
        >>>     structure = r'../0_DATA/au_9008463.cif',
        >>>     wavelength = 0.71, two_theta_range = (5,100))
        >>>
        >>> # (2) Show/save/work with the results
        >>> print(XRD.diffractions)   # use arbitrary methods 
        >>> XRD.print_diffractions()  # use inherited PXRDcalculation methods
        '''
        
        # Object description
        self.description = description
        
        # Auxiliary sub-objects: Crystal, Experiment, PlotParameters 
        crystal = Crystal(
            structure, temp_factors)
        simu_parameters = SimuParams(
            wavelength, two_theta_range, peak_profile, peak_profile_sigma)
        plot_parameters = PlotParams(
            plot_params['title'], plot_params['x_axis'], plot_params['xlim'])

        # The remaining properties and methods
        # are inherited from PXRDcalculation object,
        # which is calculated by means of above-defined sub-objects.
        PXRDcalculation.__init__(self,  
            crystal, simu_parameters, plot_parameters, peak_profile_sigma)
        
    
class ELD_polycrystal:
    '''
    Class defining *ELD_polycrystal* objects.
    
    * *ELD_polycrystal* object = diffractogram + processing-methods + results.
    * *ELD_polycrystal* offers simle OO-processing (data + functions together).
    
    TODO :: this class is under construction.

    Technical note
    
    * PO-processing (traditional, kept for compatibility and special cases).
        - Run funcs one-by-one (you need to save intermediate data/results).
    * OO-processing (new, simplified interface, better for most cases).
        - Define object and run methods (data/results are saved in the object).
    '''


    
    def __init__(self, diffractogram, itype='16bit', description=None):
        '''
        Initialize ELD_polycrystal object.

        Parameters
        ----------
        diffractogram : array or str or PathLike object 
            Source 2D diffraction pattern.
            This diffraction pattern is to be further processed
            by means of the methods defined in this class.
        itype : str, optional, default is '16bit'
            Type of the input image/array.
            We can work with grayscale images/arrays containing
            '8bit' or '16bit' values = np.uint8 or np.uint16 integers.
        description : str, optional, default is None
            Description of the source diffractogram.
            Optional, but recommended parameter.
            It makes the code self-documented and clear.

        Returns
        -------
        ELD_polycrystal object
            The object contains diffractogram (as np.array) + methods for
            the processing of the diffractogram. When the processing is
            finished, the results are saved in the object properties,
            as illustrated below.
        
        Example
        -------
        
        >>> # EDIFF :: process powder electron diffration pattern
        >>> import ediff as ed
        >>>
        >>> # (1) Read and show a powder electron diffractogram
        >>> ELD = ed.pcryst.ELD_polycrystal('diff.png', description='Au ncryst')
        >>> ELD.show_diffractogram(icut=200)
        >>>
        >>> # (2) Find the diffractogram center and show the results
        >>> ELD.find_center(detection='intensity', refinement='sum')
        >>> ELD.center.visualize_results()
        '''
        
        self.description = description
        self.read_diffractogram(diffractogram, itype)
    
       
    def read_diffractogram(self, diffractogram, itype='16bit'):
        '''
        Read diffractogram and save it in self.diffractogram object.
        
        * This method is a wrapper around ediff.io.Diffractogram.read function.

        Parameters
        ----------
        diffractogram : string or path-like object or numpy array
            Image/array, which represent diffractogram
            that should be read into numpy 2D array.
        itype : str, optional, default is 16bit
            Type of the image/array.
            We accept 8 or 16 bit grayscale images/arrays.
            This corresponds to numpy.uint8 or numpy.uint16 values.

        Returns
        -------
        numpy.ndarray
            The diffractogram is read into self.diffractogram
            and returned as numpy.ndarray.
        '''
        
        self.diffractogram = ediff.io.Diffractogram.read(diffractogram, itype)
        return(self.diffractogram)
    
    
    def show_diffractogram(self, 
        title=None, icut=None, origin=None, out_file=None, out_dpi=300):
        '''
        Show diffractogram saved in self.diffractogram object.
        
        * This method is a wrapper around ediff.io.Diffractogram.show function.

        Parameters
        ----------
        title : tr, optional, default is None
            If given, then it is the title of the plot.
        icut : integer, optional, default is None
            Upper limit of intensity shown in the diffractogram.
            The argument *icut* is used as *vmax* in plt.imshow function.
            Example: If *icut*=300, then all intensities >300 are set to 300.
        origin : 'upper' or 'lower' or None, optional, default is None
            Orientation of the image during final rendering.
            If the argument is None, we follow the Matplotlib default,
            which is *origin*='upper' = [0,0] in the upper left corner.
            Alternative: *origin*='lower' = [0,0] is in the lower left corner.
        out_file : str, optional, default is None
            Name of the output file.
            If the argument is not None, the plot is saved to *output_file*.
        out_dpi : int, optional, default is 300
            Resolution of the output file.

        Returns
        -------
        None
            The diffratogram is shown/plotted in the stdout/screen.
            If {out_file} argument is given, it is also saved in {out_file}.
        '''
        
        ediff.io.Diffractogram.show(self.diffractogram, 
            title=title, icut=icut, origin=origin,
            out_file=out_file, out_dpi=out_dpi)
    
    
    def find_center(self, **kwargs): 
        '''
        Find center of the diffractogram.

        Parameters
        ----------
        **kwargs
            All arguments are forwarded to ediff.center.CenterLocator.
            The only exception is the first argument of CenterLocator
            (input_image), which is auto-replaced by self.diffractogram.
            See the documentation ediff.center.CenterLocator 
            for the full list of options.
            
        Selected important parameters
        -----------------------------
        * detection : center detection method
        * refinement : center refinement method
        * icut : intensity cut; to cut too high intensity of primary beam
        
        Returns
        -------
        None
            The results are saved in *self.center*,
            which is ediff.center.CenterLocator object.
            Therefore, we can use all props/methods of the
            ediff.center.CenterLocator object to work with self.center.
        '''
        self.center = ediff.center.CenterLocator(self.diffractogram, **kwargs)
        
        
class Comparison:
    '''
    Final comparison of processed ELD and XRD powder diffractograms.
    
    * We compare the processed ELD-profile and XRD-profile.
    * ELD-profile - from the processed ediff.pcryst.ELD_polycrystal object.
    * XRD-profile - from the processed ediff.pcryst.XRD_polycrystal object.
    
    TODO :: this class is under construction.
    '''
    
    
    def __init__(self, ELD, XRD):
        '''
        Initialize *Comparison* = object comparing ELD and XRD profiles.

        Parameters
        ----------
        ELD : ediff.pcryst.ELD_polycrystal object
            The processed ELD diffractogram.
            The object contains ELD.profile, which is used in plotting.
        XRD : ediff.pcryst.XRD_polycrystal object
            The processed XRD diffractogram.
            The object contains XRD.profile, which is used in plotting.

        Returns
        -------
        ediff.pcryst.Comparison object
        '''
        self.ELD = ELD
        self.XRD = XRD
        
    
    def show_final_plot(self, fine_tune=1.00, out_file=None, out_dpi=300):
        '''
        Show final plot that compares self.ELD and self.XRD profiles.

        Parameters
        ----------
        fine_tune : float, optional, default is 1.00
            The fine tuning constant.
            It multiplies all X-values in ELD.profile
            to get perfect fit between ELD and XRD-profiles.
            The value of *fine_tune* constant should be close to 1.
        out_file : str or PathLike object, optional, default is None
            The name of the output file.
            If out_file = None (default), the plot is just shown, not saved.
        out_dpi : int, optional, default is 300
            The DPI of the output file = plot = image of ELD and XRD profiles.

        Returns
        -------
        None
            The result is the plot shown on the screen.
            If *out_file* parameter is given, the plot is also saved.
        '''
        
        # NOTE 1   : This func should be a wrapper of io.plot_final_eld_and_xrd
        # Reason 1 : Not to duplicate code!
        # Reason 2 : To preserve the PO-interface.
        
        # NOTE 2 : {fine_tune} constant should be saved to self.fine_tune
        # Reason : It will be used in the following self.save_final_profiles.
        self.fine_tune = fine_tune
        
        pass
    
    
    def save_final_profiles(self, out_file):
        '''
        Save final ELD and XRD profiles for possible future use.
        
        * XRD profile is already saved in XRD_polycrystal object,
          but here we save it together with ELD_profile
          (convenient for possible future plotting).
        * ELD profile is already saved in ELD_polycrystal object,
          but here we save it multiplied by *self.fine_tune*
          (so that it exactly corresponded to XRD_profile)
          and together with XRD_profile
          (convenient for possible future plotting).
          
        Returns
        -------
        None
            The final ELD and XRD profiles are saved in *out_file*.
        '''
            
        pass


# =============================================================================
# Additional tool that updates signature of wrapped functions.
# * __signature__ = function parameters shown in iPython, Spyder, JLab ...
# * __doc__ = docstring is not updated - intentionally, this is error-prone
# * additional params (__name__, __module__)
#   could be updated with existing functools.update_wrapper
#   BUT we do not use it at the moment - not necessary or even confusing
# * this tool MUST BE OUTSIDE class definitions
#   (more info in AI/ChGPT, from which this code was received and adjusted

import inspect

def _update_wrapper_signature(original_function, wrapper_function):
    sig = inspect.signature(original_function)
    sig = sig.replace(parameters=list(sig.parameters.values())[1:])
    wrapper_function.__signature__ = sig

_update_wrapper_signature(
    ediff.center.CenterLocator, ELD_polycrystal.find_center)        
